language: cpp

before_script:
  - eval "${BEFORE_SCRIPT}"

script:
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - cmake --build . -- -j2

jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
      install:
        - pip install --user conan cmake
      env:
        - BEFORE_SCRIPT="CC=gcc-9 && CXX=g++-9"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-9
      install:
        - pip install --user conan cmake
      env:
        - BEFORE_SCRIPT="CC=clang-9 && CXX=clang++-9"

    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          update: true
          packages:
            - gcc@9
            - conan
            - cmake
      env:
        - BEFORE_SCRIPT="CC=gcc-9 && CXX=g++-9"

    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          update: true
          packages:
            - conan
            - cmake
