version: v0.1.4-appveyor{build}

image:
  - Visual Studio 2019

clone_folder: C:\Projects\littlefs-utils

environment:
  matrix:
    - ARCH: x64
      STATIC_CRT: ON
    - ARCH: x64
      STATIC_CRT: OFF

install:
  - cmd: git submodule update --init --recursive
  - cmd: set PATH=C:\Python39\Scripts;%PATH%
  - cmd: pip install conan

build_script:
  - cmd: |
      mkdir build
      cd build
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
      set LITTLEFS_UTILS_VERSION=%APPVEYOR_BUILD_VERSION%
      cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DSTATIC_CRT=%STATIC_CRT% ..
      cmake --build .
      if "%STATIC_CRT%"=="ON" (set SUFFIX=%ARCH%-static) else (set SUFFIX=%ARCH%)
      move /y bin\littlefs-extract.exe bin\littlefs-extract-%SUFFIX%.exe

artifacts:
  - path: build\bin\*.exe
    name: Windows executables

deploy:
  - provider: GitHub
    auth_token:
      secure: VGIdTmInN6q55lkHcbo6tUCrm/vgbomagZ+p3wAu94IE2+mgk9jPvGVLjjPrwle7
    artifact: Windows executables
    draft: false
    prerelease: false
    on:
      branch: master
